# Generated by Django 5.2.5 on 2025-08-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grow',
            old_name='name',
            new_name='title',
        ),
    ]
